# Default values for dance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

openshift-gitops:
  enabled: true
  channel: gitops-1.10
  argocd-namespace: developer-argocd
  workload-namespaces:
    - default
openshift-pipelines:
  enabled: true
  channel: pipelines-1.12
quay:
  enabled: true
  registry: quay.io
  username: admin
  password: admin

# Private values
# You may want to override those variables in another file (e.g. values-private.yaml)
acs:
  central-endpoint: central.acs.mycluster.com:443
  api-token: eyAbC123...acs...890XyZ
developer-hub:
  # This should be removed once RHDH is GA
  quay-token: eyAbC123...rhdh...890XyZ
